version: '3.1'
services:
  sbapp:
    restart: on-failure
    container_name: app-stockprices
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8110:8110"
    depends_on:
      - kafka
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181